import 'dart:typed_data';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../services/panchang_service.dart';
import 'dart:html' as html if (dart.library.html);

/// Service to generate comprehensive PDF reports
class PdfReportService {
  static final PdfReportService _instance = PdfReportService._internal();
  factory PdfReportService() => _instance;
  PdfReportService._internal();

  static const List<String> _signs = [
    'Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo',
    'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'
  ];

  static const List<String> _planets = [
    'Sun', 'Moon', 'Mars', 'Mercury', 'Jupiter', 'Venus', 'Saturn', 'Rahu', 'Ketu'
  ];

  /// Generate a comprehensive birth chart report
  Future<Uint8List> generateBirthChartReport({
    required String name,
    required DateTime birthDate,
    required String birthTime,
    required String birthPlace,
    required double latitude,
    required double longitude,
    required Map<String, dynamic> chartData,
    Map<String, dynamic>? dashaData,
  }) async {
    final pdf = pw.Document();
    final panchang = await PanchangService().getTodayPanchang();
    
    // Title Page
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            pw.SizedBox(height: 100),
            pw.Container(
              padding: const pw.EdgeInsets.all(20),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.amber, width: 3),
                borderRadius: pw.BorderRadius.circular(16),
              ),
              child: pw.Column(
                children: [
                  pw.Text('॥ श्री गणेशाय नमः ॥',
                    style: pw.TextStyle(fontSize: 18, color: PdfColors.orange800)),
                  pw.SizedBox(height: 10),
                  pw.Text('KUNDLI',
                    style: pw.TextStyle(fontSize: 36, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo900)),
                  pw.Text('Birth Chart Report',
                    style: pw.TextStyle(fontSize: 18, color: PdfColors.grey700)),
                ],
              ),
            ),
            pw.SizedBox(height: 60),
            pw.Text(name.toUpperCase(),
              style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 40),
            _buildInfoRow('Date of Birth', '${birthDate.day}/${birthDate.month}/${birthDate.year}'),
            _buildInfoRow('Time of Birth', birthTime),
            _buildInfoRow('Place of Birth', birthPlace),
            _buildInfoRow('Latitude', '${latitude.toStringAsFixed(4)}° N'),
            _buildInfoRow('Longitude', '${longitude.toStringAsFixed(4)}° E'),
            pw.SizedBox(height: 40),
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColors.amber50,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                children: [
                  pw.Text('Ascendant (Lagna): ${chartData['ascendant_sign'] ?? 'N/A'}',
                    style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 8),
                  pw.Text('Moon Sign (Rashi): ${_getMoonSign(chartData)}',
                    style: pw.TextStyle(fontSize: 14)),
                  pw.SizedBox(height: 4),
                  pw.Text('Moon Nakshatra: ${chartData['moon_nakshatra'] ?? 'N/A'}',
                    style: pw.TextStyle(fontSize: 14)),
                ],
              ),
            ),
            pw.Spacer(),
            pw.Text('Generated by karmgyan Astrology',
              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
            pw.Text('Report Date: ${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}',
              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
          ],
        ),
      ),
    );

    // Panchang at Birth
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _buildSectionHeader('Panchang at Birth'),
            pw.SizedBox(height: 20),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey400),
              children: [
                _buildTableRow('Tithi', panchang['tithi'] ?? 'N/A'),
                _buildTableRow('Nakshatra', panchang['nakshatra'] ?? 'N/A'),
                _buildTableRow('Yoga', panchang['yoga'] ?? 'N/A'),
                _buildTableRow('Karana', panchang['karana'] ?? 'N/A'),
                _buildTableRow('Vara (Day)', panchang['vara'] ?? 'N/A'),
                _buildTableRow('Sunrise', panchang['sunrise'] ?? 'N/A'),
                _buildTableRow('Sunset', panchang['sunset'] ?? 'N/A'),
              ],
            ),
            pw.SizedBox(height: 30),
            _buildSectionHeader('Planetary Positions'),
            pw.SizedBox(height: 20),
            _buildPlanetTable(chartData),
          ],
        ),
      ),
    );

    // House Details
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _buildSectionHeader('House (Bhava) Details'),
            pw.SizedBox(height: 20),
            _buildHouseTable(chartData),
            pw.SizedBox(height: 30),
            _buildSectionHeader('Chart Analysis'),
            pw.SizedBox(height: 20),
            _buildAnalysis(chartData),
          ],
        ),
      ),
    );

    // Dasha Page
    if (dashaData != null) {
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildSectionHeader('Vimshottari Dasha'),
              pw.SizedBox(height: 10),
              pw.Text('The Vimshottari Dasha system is a predictive tool based on the position of Moon at birth.',
                style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700)),
              pw.SizedBox(height: 20),
              _buildDashaTable(dashaData),
            ],
          ),
        ),
      );
    }

    // Predictions Page
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _buildSectionHeader('Life Predictions Overview'),
            pw.SizedBox(height: 20),
            _buildPredictionSection('Career', _getCareerPrediction(chartData)),
            _buildPredictionSection('Marriage & Relationships', _getMarriagePrediction(chartData)),
            _buildPredictionSection('Health', _getHealthPrediction(chartData)),
            _buildPredictionSection('Finance', _getFinancePrediction(chartData)),
            _buildPredictionSection('Spiritual Growth', _getSpiritualPrediction(chartData)),
          ],
        ),
      ),
    );

    // Remedies Page
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _buildSectionHeader('Recommended Remedies'),
            pw.SizedBox(height: 20),
            ..._getRemedies(chartData).map((remedy) => pw.Container(
              margin: const pw.EdgeInsets.only(bottom: 12),
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey100,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(remedy['title']!, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 4),
                  pw.Text(remedy['description']!, style: pw.TextStyle(fontSize: 11)),
                ],
              ),
            )).toList(),
            pw.Spacer(),
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.amber),
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                children: [
                  pw.Text('Note:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 8),
                  pw.Text(
                    'This report is generated based on Vedic astrology principles. '
                    'Predictions are indicative and should be used for guidance only. '
                    'Free will and karma play important roles in shaping one\'s destiny.',
                    style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
                    textAlign: pw.TextAlign.center,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );

    return pdf.save();
  }

  /// Share/Print the PDF
  Future<void> sharePdf(Uint8List pdfData, String fileName) async {
    try {
      // On web, use download instead of share
      if (kIsWeb) {
        // Create a blob URL and trigger download
        final blob = html.Blob([pdfData]);
        final url = html.Url.createObjectUrlFromBlob(blob);
        final anchor = html.AnchorElement(href: url)
          ..setAttribute('download', fileName)
          ..click();
        html.Url.revokeObjectUrl(url);
      } else {
        // On mobile, use the printing package
        await Printing.sharePdf(bytes: pdfData, filename: fileName);
      }
    } catch (e) {
      // Fallback: try layoutPdf
      try {
        await Printing.layoutPdf(onLayout: (format) => pdfData);
      } catch (e2) {
        throw Exception('Failed to share PDF: $e2');
      }
    }
  }

  /// Print the PDF directly
  Future<void> printPdf(Uint8List pdfData) async {
    await Printing.layoutPdf(onLayout: (format) => pdfData);
  }

  // Helper methods
  pw.Widget _buildInfoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.center,
        children: [
          pw.Text('$label: ', style: pw.TextStyle(color: PdfColors.grey700)),
          pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  pw.Widget _buildSectionHeader(String title) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 16),
      decoration: pw.BoxDecoration(
        color: PdfColors.indigo900,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Text(title, style: pw.TextStyle(color: PdfColors.white, fontSize: 16, fontWeight: pw.FontWeight.bold)),
    );
  }

  pw.TableRow _buildTableRow(String label, String value) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(value),
        ),
      ],
    );
  }

  pw.Widget _buildPlanetTable(Map<String, dynamic> chartData) {
    final planets = chartData['planets'] as List<dynamic>? ?? [];
    
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey400),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(2),
        2: const pw.FlexColumnWidth(1.5),
        3: const pw.FlexColumnWidth(1),
        4: const pw.FlexColumnWidth(2),
      },
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: PdfColors.amber100),
          children: ['Planet', 'Sign', 'Degrees', 'House', 'Nakshatra'].map((h) => 
            pw.Padding(
              padding: const pw.EdgeInsets.all(8),
              child: pw.Text(h, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            )
          ).toList(),
        ),
        ...planets.map((p) => pw.TableRow(
          children: [
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text(p['name'] ?? '')),
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text(p['sign'] ?? '')),
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text('${(p['degrees_in_sign'] as num?)?.toStringAsFixed(2) ?? '0'}°')),
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text('${p['house'] ?? ''}')),
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text(p['nakshatra'] ?? '')),
          ],
        )).toList(),
      ],
    );
  }

  pw.Widget _buildHouseTable(Map<String, dynamic> chartData) {
    final houses = chartData['houses'] as List<dynamic>? ?? [];
    final planets = chartData['planets'] as List<dynamic>? ?? [];
    
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey400),
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: PdfColors.amber100),
          children: ['House', 'Sign', 'Planets'].map((h) => 
            pw.Padding(
              padding: const pw.EdgeInsets.all(8),
              child: pw.Text(h, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            )
          ).toList(),
        ),
        ...houses.map((h) {
          final houseNum = h['number'] as int;
          final planetsInHouse = planets
            .where((p) => p['house'] == houseNum)
            .map((p) => p['name'])
            .join(', ');
          return pw.TableRow(
            children: [
              pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text('House $houseNum')),
              pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text(h['sign'] ?? '')),
              pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text(planetsInHouse.isEmpty ? '-' : planetsInHouse)),
            ],
          );
        }).toList(),
      ],
    );
  }

  pw.Widget _buildDashaTable(Map<String, dynamic> dashaData) {
    final mahadashas = dashaData['mahadashas'] as List<dynamic>? ?? [];
    
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey400),
      children: [
        pw.TableRow(
          decoration: pw.BoxDecoration(color: PdfColors.amber100),
          children: ['Mahadasha', 'Start Date', 'End Date', 'Duration'].map((h) => 
            pw.Padding(
              padding: const pw.EdgeInsets.all(8),
              child: pw.Text(h, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            )
          ).toList(),
        ),
        ...mahadashas.take(9).map((d) => pw.TableRow(
          children: [
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text(d['planet'] ?? '')),
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text(d['start_date'] ?? '')),
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text(d['end_date'] ?? '')),
            pw.Padding(padding: const pw.EdgeInsets.all(6), child: pw.Text('${d['duration_years'] ?? ''} years')),
          ],
        )).toList(),
      ],
    );
  }

  pw.Widget _buildAnalysis(Map<String, dynamic> chartData) {
    final ascSign = chartData['ascendant_sign'] ?? 'Unknown';
    final moonSign = _getMoonSign(chartData);
    
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Lagna (Ascendant) Analysis:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
        pw.Text(_getLagnaAnalysis(ascSign), style: pw.TextStyle(fontSize: 11)),
        pw.SizedBox(height: 16),
        pw.Text('Moon Sign Analysis:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
        pw.Text(_getMoonAnalysis(moonSign), style: pw.TextStyle(fontSize: 11)),
      ],
    );
  }

  pw.Widget _buildPredictionSection(String title, String prediction) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 16),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 13)),
          pw.SizedBox(height: 6),
          pw.Text(prediction, style: pw.TextStyle(fontSize: 11, color: PdfColors.grey800)),
        ],
      ),
    );
  }

  String _getMoonSign(Map<String, dynamic> chartData) {
    final planets = chartData['planets'] as List<dynamic>? ?? [];
    final moon = planets.firstWhere((p) => p['name'] == 'Moon', orElse: () => {});
    return moon['sign'] ?? 'Unknown';
  }

  String _getLagnaAnalysis(String sign) {
    final analyses = {
      'Aries': 'Strong leadership qualities, pioneering spirit, and natural courage define this ascendant.',
      'Taurus': 'Stable, practical, and with a strong appreciation for beauty and comfort.',
      'Gemini': 'Quick-witted, communicative, and adaptable with a curious mind.',
      'Cancer': 'Nurturing, emotionally sensitive, and deeply connected to home and family.',
      'Leo': 'Charismatic, creative, and natural leader with a generous heart.',
      'Virgo': 'Analytical, detail-oriented, and service-minded with practical wisdom.',
      'Libra': 'Diplomatic, fair-minded, and with a strong sense of justice and harmony.',
      'Scorpio': 'Intense, transformative, and deeply perceptive with strong willpower.',
      'Sagittarius': 'Optimistic, philosophical, and freedom-loving with a love for adventure.',
      'Capricorn': 'Ambitious, disciplined, and practical with strong organizational skills.',
      'Aquarius': 'Innovative, humanitarian, and independent with progressive ideas.',
      'Pisces': 'Intuitive, compassionate, and spiritually inclined with artistic talents.',
    };
    return analyses[sign] ?? 'Analysis not available for this sign.';
  }

  String _getMoonAnalysis(String sign) {
    final analyses = {
      'Aries': 'Emotionally energetic and spontaneous. Quick to react but equally quick to recover.',
      'Taurus': 'Emotionally stable and security-conscious. Values comfort and consistency.',
      'Gemini': 'Mentally active with fluctuating emotions. Communication brings emotional satisfaction.',
      'Cancer': 'Deeply emotional and nurturing. Strong attachment to home and family.',
      'Leo': 'Emotionally warm and generous. Needs recognition and appreciation.',
      'Virgo': 'Analytical about emotions. Finds comfort in being helpful and organized.',
      'Libra': 'Seeks emotional balance and harmony. Values relationships deeply.',
      'Scorpio': 'Intense and passionate emotions. Deep need for emotional intimacy.',
      'Sagittarius': 'Optimistic emotional nature. Needs freedom and adventure for happiness.',
      'Capricorn': 'Reserved emotional expression. Values achievement and status.',
      'Aquarius': 'Detached emotional nature. Values friendship and humanitarian causes.',
      'Pisces': 'Highly intuitive and empathetic. Spiritually inclined with artistic sensitivity.',
    };
    return analyses[sign] ?? 'Analysis not available for this sign.';
  }

  String _getCareerPrediction(Map<String, dynamic> chartData) {
    return 'Based on the 10th house and its lord, along with the placement of Saturn, '
           'you have potential for success in structured environments. Your natural abilities '
           'and the planetary positions suggest opportunities in leadership, management, or specialized fields.';
  }

  String _getMarriagePrediction(Map<String, dynamic> chartData) {
    return 'The 7th house and Venus placement indicate the nature of partnerships. '
           'You are likely to find a partner who complements your personality. '
           'Mutual respect and understanding will be key factors in relationship success.';
  }

  String _getHealthPrediction(Map<String, dynamic> chartData) {
    return 'The 6th house indicates general health patterns. Regular exercise and '
           'balanced diet are recommended. Pay attention to stress management and '
           'ensure adequate rest for optimal well-being.';
  }

  String _getFinancePrediction(Map<String, dynamic> chartData) {
    return 'The 2nd and 11th houses indicate financial potential. With proper planning '
           'and disciplined approach, wealth accumulation is favorable. Avoid impulsive '
           'spending and focus on long-term investments.';
  }

  String _getSpiritualPrediction(Map<String, dynamic> chartData) {
    return 'The 9th and 12th houses suggest spiritual inclinations. You have natural '
           'wisdom and the capacity for spiritual growth. Regular meditation and '
           'connection with higher teachings will enhance your spiritual journey.';
  }

  List<Map<String, String>> _getRemedies(Map<String, dynamic> chartData) {
    return [
      {'title': 'Mantra Recitation', 'description': 'Recite Gayatri Mantra 108 times daily for overall protection and spiritual growth.'},
      {'title': 'Charity', 'description': 'Donate food to the needy on Saturdays to pacify Saturn\'s influence.'},
      {'title': 'Gemstone', 'description': 'Consult an astrologer for personalized gemstone recommendations based on your chart.'},
      {'title': 'Fasting', 'description': 'Observing fast on days associated with beneficial planets can strengthen their positive effects.'},
      {'title': 'Meditation', 'description': 'Practice meditation during Brahma Muhurta (pre-dawn) for spiritual advancement.'},
    ];
  }
}

